// data.js
const data = [
    {
      id: 1,
      title: 'House Luxury',
      secondtitle: 'New York City',
      price: 150000,
      status: 'For Sale',
      area: 720,
      rooms: 5,
      beds: 1,
      baths: 4,
      recentProperties: true,
      yearbuilt: '10/6/2020',
      garages: 2,
      armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
      video: 'https://www.youtube.com/watch?v=14semTlwyUY',
      wallpaper: require('./assets/images/id-1/wallpaper.jpg'),
      images: [ 
        require('./assets/images/id-3/wallpaper.jpg'),
        require('./assets/images/id-2/wallpaper.jpg'),
        require('./assets/images/id-4/wallpaper.jpg'),
        require('./assets/images/id-5/wallpaper.jpg'),
        require('./assets/images/id-6/wallpaper.jpg'),
     ],
     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
    },
    {
        id: 2,
        title: 'House Luxury',
        secondtitle: 'Los Angeles',
        price: 6400,
        status: 'For Sale',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-2/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 3,
        title: 'House Luxury',
        secondtitle: 'San Francisco',
        price: 220000,
        status: 'For Sale',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-3/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 4,
        title: 'House Luxury',
        secondtitle: 'Miami FL',
        price: 44000,
        status: 'For Sale',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        recentProperties: true,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-4/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 5,
        title: 'House Luxury',
        secondtitle: 'Chicago IL',
        price: 33899,
        status: 'For Sale',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-5/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 6,
        title: 'House Luxury',
        secondtitle: 'Toronto CA',
        price: 66777,
        status: 'For Sale',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        recentProperties: true,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-6/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 7,
        title: 'House Luxury',
        secondtitle: 'Toronto CA',
        price: 780,
        status: 'For Rent',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-7/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 8,
        title: 'House Luxury',
        secondtitle: 'Toronto CA',
        price: 1020,
        status: 'For Rent',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-8/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 9,
        title: 'House Luxury',
        secondtitle: 'Chicago IL',
        price: 667,
        status: 'For Rent',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-9/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      },
      {
        id: 10,
        title: 'House Luxury',
        secondtitle: 'Toronto CA',
        price: 1200,
        status: 'For Rent',
        area: 720,
        rooms: 5,
        beds: 1,
        baths: 4,
        yearbuilt: '10/6/2020',
        garages: 2,
        armenities: [ 'Air Cond', 'Dishwater', 'Parking', 'Balcony', 'Pool' , 'Internet' ,'Cable TV','Fridge'],
        video: 'https://www.youtube.com/watch?v=14semTlwyUY',
        wallpaper: require('./assets/images/id-10/wallpaper.jpg'),
        images: [ 
          require('./assets/images/id-1/1.jpg'),
          require('./assets/images/id-1/2.jpg'),
          require('./assets/images/id-1/3.jpg'),
          require('./assets/images/id-1/4.jpg'),
          require('./assets/images/id-1/5.jpg'),
       ],
       description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit, alias fuga aliquam quod tempora a nisi esse magnam nulla quas! Error praesentium, vero dolorum laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum rerum beatae consequatur, totam fugit.'
      }
  ];
  
  export default data;
  